apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
spec:
  selector:
    app: schema-registry
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
    spec:
      containers:
      - name: schema-registry
        image: confluentinc/cp-schema-registry
        ports:
        - containerPort: 8081
        env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema-registry
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: "kafka:29092"
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        - name: SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS
          value: "GET,POST,PUT,DELETE,OPTIONS"
        - name: SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_HEADERS
          value: "Content-Type"
        - name: SCHEMA_REGISTRY_DEBUG
          value: "true"